name: CI/CD - OnlineAnket AWS Deployment

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: onlineanketdb
          MYSQL_ROOT_PASSWORD: 1234
        ports:
          - 3306:3306
 
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -p1234"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
      - name: Kodu Çek
        uses: actions/checkout@v4

      - name: JDK 17 Kurulumu
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17' # Senin projen Java 17
          cache: maven

      - name: Maven ile Derle ve Test Et
        env:
     
          SPRING_DATASOURCE_URL: jdbc:mysql://127.0.0.1:3306/onlineanketdb?useSSL=false&allowPublicKeyRetrieval=true
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: 1234
        run: mvn -B clean package

      - name: JAR Dosyasını EC2'ye Gönder
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "target/*.jar"
          target: "/home/ec2-user/onlineanket"
          strip_components: 1

      - name: Sunucuda Uygulamayı Başlat
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
        
            sudo fuser -k 8080/tcp || true
            
         
            mkdir -p /home/ec2-user/onlineanket
            cd /home/ec2-user/onlineanket
            
           
            nohup java -jar onlineanket-0.0.1-SNAPSHOT.jar --spring.datasource.username=admin > app.log 2>&1 &
